[2024-08-04T19:25:29.072+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-04T19:25:29.103+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_loan_holiday.End manual__2024-08-04T19:24:48.063538+00:00 [queued]>
[2024-08-04T19:25:29.112+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_loan_holiday.End manual__2024-08-04T19:24:48.063538+00:00 [queued]>
[2024-08-04T19:25:29.113+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-04T19:25:29.127+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): End> on 2024-08-04 19:24:48.063538+00:00
[2024-08-04T19:25:29.134+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'refresh_loan_holiday', 'End', 'manual__2024-08-04T19:24:48.063538+00:00', '--job-id', '804', '--raw', '--subdir', 'DAGS_FOLDER/fill_tables.py', '--cfg-path', '/tmp/tmp7i7h_7v8']
[2024-08-04T19:25:29.137+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=831) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-04T19:25:29.137+0000] {standard_task_runner.py:91} INFO - Job 804: Subtask End
[2024-08-04T19:25:29.138+0000] {standard_task_runner.py:63} INFO - Started process 832 to run task
[2024-08-04T19:25:29.180+0000] {task_command.py:426} INFO - Running <TaskInstance: refresh_loan_holiday.End manual__2024-08-04T19:24:48.063538+00:00 [running]> on host 2634975b7554
[2024-08-04T19:25:29.254+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='refresh_loan_holiday' AIRFLOW_CTX_TASK_ID='End' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T19:24:48.063538+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-04T19:24:48.063538+00:00'
[2024-08-04T19:25:29.255+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-04T19:25:29.273+0000] {base.py:84} INFO - Using connection ID 'postgres_default2' for task execution.
[2024-08-04T19:25:29.295+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-04T19:25:29.296+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-04T19:25:29.304+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=refresh_loan_holiday, task_id=End, run_id=manual__2024-08-04T19:24:48.063538+00:00, execution_date=20240804T192448, start_date=20240804T192529, end_date=20240804T192529
[2024-08-04T19:25:29.353+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-04T19:25:29.379+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-04T19:25:29.382+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
