[2024-08-01T15:14:49.161+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-01T15:14:49.242+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fill_tables_on_rd.Fill_product_info manual__2024-08-01T15:06:51.553068+00:00 [queued]>
[2024-08-01T15:14:49.281+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fill_tables_on_rd.Fill_product_info manual__2024-08-01T15:06:51.553068+00:00 [queued]>
[2024-08-01T15:14:49.283+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-01T15:14:49.301+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Fill_product_info> on 2024-08-01 15:06:51.553068+00:00
[2024-08-01T15:14:49.308+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fill_tables_on_rd', 'Fill_product_info', 'manual__2024-08-01T15:06:51.553068+00:00', '--job-id', '737', '--raw', '--subdir', 'DAGS_FOLDER/fill_tables.py', '--cfg-path', '/tmp/tmpl9ng19k7']
[2024-08-01T15:14:49.311+0000] {standard_task_runner.py:91} INFO - Job 737: Subtask Fill_product_info
[2024-08-01T15:14:49.311+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1866) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-01T15:14:49.312+0000] {standard_task_runner.py:63} INFO - Started process 1869 to run task
[2024-08-01T15:14:49.385+0000] {task_command.py:426} INFO - Running <TaskInstance: fill_tables_on_rd.Fill_product_info manual__2024-08-01T15:06:51.553068+00:00 [running]> on host 2634975b7554
[2024-08-01T15:14:49.535+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fill_tables_on_rd' AIRFLOW_CTX_TASK_ID='Fill_product_info' AIRFLOW_CTX_EXECUTION_DATE='2024-08-01T15:06:51.553068+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-01T15:06:51.553068+00:00'
[2024-08-01T15:14:49.539+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-01T15:14:59.785+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-01T15:14:59.787+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fill_tables.py", line 61, in fill_product_info
    df = spark.read.csv('/opt/airflow/files/product_info.csv', sep=',', header=True, schema=schema_product_info)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/readwriter.py", line 701, in csv
    self._set_opts(
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/readwriter.py", line 51, in _set_opts
    self.schema(schema)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/readwriter.py", line 152, in schema
    jschema = spark._jsparkSession.parseDataType(schema.json())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.IllegalArgumentException: Failed to convert the JSON string 'data' to a data type.
[2024-08-01T15:14:59.823+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=fill_tables_on_rd, task_id=Fill_product_info, run_id=manual__2024-08-01T15:06:51.553068+00:00, execution_date=20240801T150651, start_date=20240801T151449, end_date=20240801T151459
[2024-08-01T15:14:59.844+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 737 for task Fill_product_info (Failed to convert the JSON string 'data' to a data type.; 1869)
[2024-08-01T15:14:59.900+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-01T15:14:59.935+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-01T15:14:59.939+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
