[2024-08-03T12:39:22.401+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-03T12:39:22.459+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fill_tables_on_rd.Fill_deal_info manual__2024-08-01T20:52:36.232608+00:00 [queued]>
[2024-08-03T12:39:22.476+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fill_tables_on_rd.Fill_deal_info manual__2024-08-01T20:52:36.232608+00:00 [queued]>
[2024-08-03T12:39:22.482+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-03T12:39:22.510+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Fill_deal_info> on 2024-08-01 20:52:36.232608+00:00
[2024-08-03T12:39:22.521+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fill_tables_on_rd', 'Fill_deal_info', 'manual__2024-08-01T20:52:36.232608+00:00', '--job-id', '764', '--raw', '--subdir', 'DAGS_FOLDER/fill_tables.py', '--cfg-path', '/tmp/tmphkylfxpu']
[2024-08-03T12:39:22.528+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=191) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-03T12:39:22.529+0000] {standard_task_runner.py:63} INFO - Started process 197 to run task
[2024-08-03T12:39:22.527+0000] {standard_task_runner.py:91} INFO - Job 764: Subtask Fill_deal_info
[2024-08-03T12:39:22.641+0000] {task_command.py:426} INFO - Running <TaskInstance: fill_tables_on_rd.Fill_deal_info manual__2024-08-01T20:52:36.232608+00:00 [running]> on host 2634975b7554
[2024-08-03T12:39:22.836+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fill_tables_on_rd' AIRFLOW_CTX_TASK_ID='Fill_deal_info' AIRFLOW_CTX_EXECUTION_DATE='2024-08-01T20:52:36.232608+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-01T20:52:36.232608+00:00'
[2024-08-03T12:39:22.838+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-03T12:39:47.112+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2024-08-03T12:39:47.280+0000] {process_utils.py:132} INFO - Sending 15 to group 197. PIDs of all processes in the group: [203, 197]
[2024-08-03T12:39:47.284+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 197
[2024-08-03T12:39:47.299+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-08-03T12:39:47.354+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-03T12:39:47.724+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fill_tables.py", line 55, in fill_deal_info
    df.write.jdbc(url=postgres_uri, table='rd.deal_info', mode='append', properties=properties)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/readwriter.py", line 1984, in jdbc
    self.mode(mode)._jwrite.jdbc(url, table, jprop)
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1321, in __call__
    answer = self.gateway_client.send_command(command)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 708, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-08-03T12:39:47.912+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=fill_tables_on_rd, task_id=Fill_deal_info, run_id=manual__2024-08-01T20:52:36.232608+00:00, execution_date=20240801T205236, start_date=20240803T123922, end_date=20240803T123947
[2024-08-03T12:39:48.320+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=197, status='terminated', exitcode=2, started='12:39:21') (197) terminated with exit code 2
[2024-08-03T12:39:48.539+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=203, status='terminated', started='12:39:21') (203) terminated with exit code None
[2024-08-03T12:39:48.550+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 143
[2024-08-03T12:39:49.100+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-08-03T12:39:49.266+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-03T12:39:49.380+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
